Правила изменены, запустил локалку и проверил - все работает без сбое…
xtray85/space-station-14 pull request #7
Opened 2023-02-25 19:23 UTC by Wywerno

…в, нужный текст есть.

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-02-25 19:24 UTC, Wywerno commented
Cool

2023-02-25 19:26 UTC, Wywerno reviewed
Все круто, давай уже пушь

2023-02-26 15:21 UTC, xtray85 commented
Исключи файл SpaceStation14.sln из пул реквеста

2023-02-26 16:13 UTC, xtray85 requested changes
Убрать файл пректа

2023-02-26 16:14 UTC, closed without merging